M48
; DRILL file KiCad 10.0.6 date 2026-09-17T02:37:16
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-17T02:37:16+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X68.43Y-45.22
X74.21Y-45.22
T2
X42.834Y-43.406
X44.0Y-73.9
X119.354Y-42.5
X119.354Y-73.9
M30
