M48
; DRILL file KiCad 10.0.6 date 2026-09-12T19:15:17
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-12T19:15:17+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X68.25Y-101.11
X68.25Y-106.89
T2
X63.0Y-43.0
X63.0Y-89.0
X131.0Y-43.0
X131.0Y-89.0
M30
