M48
; DRILL file KiCad 10.0.6 date 2026-09-13T18:37:30
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-13T18:37:30+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
%
G90
G05
T1
X94.61Y-43.25
X100.39Y-43.25
T2
X83.1Y-41.75
X89.9Y-41.75
T3
X63.5Y-55.95
X63.5Y-117.7
X100.5Y-55.95
X100.5Y-117.7
M30
